import os
import requests
import json
import time
import random

# Load environment variables from the .env file (requires python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("⚠️  'python-dotenv' module not found. Assuming environment variables are set globally.")

# The URL of your local PAN Command server
API_URL = "http://localhost:5000/api/v1/dispatch/request"

# Safely retrieve the API Key from the local environment
stripe_api_key = os.getenv("STRIPE_API_KEY")

# Defensive check: Ensure the key actually exists before making the request
if not stripe_api_key:
    raise ValueError("🚨 STRIPE_API_KEY is missing! Please ensure it is set in your .env file.")

# The headers now use the injected secret
HEADERS = {
    "Authorization": f"Bearer {stripe_api_key}",
    "Content-Type": "application/json"
}

# The automated telemetry payload generated by a broken AV
payload = {
    "asset_id": f"WAYMO-{random.randint(100, 999)}",
    "latitude": 33.415 + random.uniform(-0.02, 0.02),
    "longitude": -111.831 + random.uniform(-0.02, 0.02),
    "error_code": "sensor_cleaning",
    "notes": "LiDAR array obstructed by mud. Auto-cleaning fluid depleted."
}

print(f"🤖 [AV TELEMETRY] Fault detected on {payload['asset_id']}.")
print(f"📡 [NETWORK] Transmitting automated dispatch request to PAN Network API...\n")
time.sleep(1)

# Fire the POST request to your server
response = requests.post(API_URL, headers=HEADERS, json=payload)

# Print the results
if response.status_code == 201:
    print("✅ [PAN API] Response 201: CREATED")
    print(json.dumps(response.json(), indent=4))
else:
    print(f"❌ [PAN API] Error {response.status_code}")
    print(response.text)